### ISSUE TITLE
Results Comparison

### ISSUE THREAD

**Issue by lroberts36** [ermalrrapaj/two_phase_skyrme#1]
Perform a comparison between the results of the Fortran code, the C++ code, and the Python code to be sure we are doing everything correctly.

**Comment by ermalrrapaj** [comment]
Tested codes and they agree well.
However, there are differences in S/N due to numerics, I suspect.

**Comment by lroberts36** [comment]
Ok, I think we need to check the tabulated fermi integrals vs. direct numerical integration.  My understanding is that the tabulated fermi integrals should only have small deviations from their actual values, but we need to check that this is indeed the source of the discrepancy.

**Comment by ermalrrapaj** [comment]
If the constructor which converts from my parameters is used, there is very good agreement, the relative difference is sub percent. If the constructor which needs physical observables is used, there is a small error in the determination of chemical potentials which leads to errors in pressure values. This means that the input for physical observables must be given to high order digit precision to avoid such errors.
